/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness-проба
         * @description Проверяет, что процесс отвечает. К БД и Redis не обращается, поэтому
         *     `ok` не гарантирует доступность зависимостей.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обменять email и пароль на bearer-токен
         * @description Первый шаг подключения. Создаёт запись в `api_tokens` с TTL 24 часа и
         *     возвращает plaintext-токен — он показывается **один раз**.
         *
         *     Ограничение частоты: 5 запросов за 60 секунд с одного IP
         *     (`express-rate-limit`, заголовки draft-8).
         *
         *     Несуществующий email и неверный пароль дают идентичный 401 —
         *     перечисление пользователей невозможно.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Профиль владельца текущего токена
         * @description Проверка живости токена и получение `userId`. Пароль не возвращается
         *     никогда — маппер отдаёт только три поля.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список токенов текущего пользователя
         * @description Выборка ограничена `ApiTokenScope` (`user_id = <текущий>` и
         *     `type = 'personal'`): чужие токены не попадают ни в `data`, ни в
         *     `meta.total`, а сессионные токены из `POST /api/auth/login` не
         *     возвращаются вовсе — ими пользователь не управляет. Фильтров нет.
         *
         *     Поля `token` в ответе нет: секрет показывается только в момент выпуска.
         */
        get: operations["listApiTokens"];
        put?: never;
        /**
         * Выпустить API-токен
         * @description Долгоживущий токен для интеграций и CI. Принадлежит владельцу
         *     предъявленного токена — выпустить ключ «за другого пользователя» нельзя.
         *
         *     `expiresAt` необязателен: принимается ISO-строка, `null` или
         *     отсутствие поля. Без даты токен бессрочен и отзывается только
         *     через `DELETE /api/tokens/{id}`.
         */
        post: operations["createApiToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор API-токена */
                id: components["parameters"]["TokenId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Отозвать токен
         * @description Физически удаляет строку — отзыв действует немедленно. Удаление
         *     собственного токена равносильно logout: следующий запрос с ним даст 401.
         *
         *     Порядок проверок: `findById` → 404 → `ApiTokenPolicy.delete` → 403 → удаление.
         */
        delete: operations["deleteApiToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список форм текущего пользователя
         * @description `FormScope` жёстко ограничивает выборку `user_id = <текущий>`, поэтому
         *     чужие публичные формы сюда не попадают — публичный доступ есть только
         *     у `GET /api/forms/{id}`.
         *
         *     Сортировка фиксирована: `created_at DESC`.
         */
        get: operations["listForms"];
        put?: never;
        /**
         * Создать форму
         * @description `userId` берётся из токена; передать его в теле нельзя — Zod отбросит поле.
         *
         *     Созданная форма всегда имеет `status: "draft"` — `published_at` и
         *     `archived_at` не входят в `creatableColumns`/`updatableColumns`.
         *     Открывается форма отдельным вызовом `POST /api/forms/{id}/publish`.
         */
        post: operations["createForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        /**
         * Получить форму со схемой
         * @description Единственный эндпоинт с анонимным доступом к содержимому формы —
         *     используется и редактором владельца, и рендером публичной формы.
         *
         *     `OptionalAuthMiddleware` пропускает запрос без заголовка, но битый или
         *     просроченный токен всё равно даёт 401. Дальше решает `FormPolicy.view`:
         *
         *     | Кто | Опубликована | Draft / scheduled / archived |
         *     |---|---|---|
         *     | Аноним | 200 | 401 |
         *     | Владелец | 200 | 200 |
         *     | Другой пользователь | 200 | 403 |
         */
        get: operations["getForm"];
        put?: never;
        post?: never;
        /**
         * Удалить форму
         * @description Необратимо. Внешний ключ `form_responses.form_id` объявлен с
         *     `ON DELETE CASCADE`, поэтому вместе с формой удаляются все её ответы.
         */
        delete: operations["deleteForm"];
        options?: never;
        head?: never;
        /**
         * Обновить форму
         * @description Частичное обновление: все поля необязательны, переданные — перезаписывают
         *     текущие значения, остальные не трогаются. Пустое тело отклоняется
         *     миддлварой `validate` (400).
         */
        patch: operations["updateForm"];
        trace?: never;
    };
    "/api/forms/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Опубликовать форму
         * @description Проставляет `published_at`, после чего форма и её роуты ответов
         *     открываются анонимному доступу.
         *
         *     Тело необязательно. Без него публикация происходит сразу
         *     (`status: "published"`, `isPublic: true`); с `date` в будущем —
         *     отложенная публикация (`status: "scheduled"`, форма пока непублична).
         *
         *     Допустимо из `draft` и `scheduled` (второе — перепланирование даты).
         *     Из `published` нужен сначала `unpublish`, из `archived` — `unarchive`.
         *     Только владелец (`FormPolicy.update`).
         */
        post: operations["publishForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Снять форму с публикации
         * @description Сбрасывает `published_at` в `NULL`, возвращая форму в `draft`. Тем же
         *     вызовом отменяется запланированная публикация.
         *
         *     Собранные ответы остаются на месте, но доступ к незаконченным
         *     черновикам закрывается вместе с формой: `FormResponsePolicy`
         *     спрашивает `FormPolicy.view` родителя.
         *
         *     Допустимо из `published` и `scheduled`. Из `archived` нужен сначала
         *     `unarchive`. Тело запроса не требуется.
         *     Только владелец (`FormPolicy.update`).
         */
        post: operations["unpublishForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Архивировать форму
         * @description Проставляет `archived_at`: форма перестаёт быть публичной, приём новых
         *     ответов закрывается. Данные и ответы остаются на месте, владелец
         *     продолжает видеть форму и выгружать ответы. `published_at` не
         *     затирается, поэтому `unarchive` вернёт форму в прежнее состояние.
         *
         *     Тело необязательно. С `date` в будущем архивация откладывается: до
         *     наступления даты статус не меняется, так как `resolveFormStatus`
         *     учитывает `archived_at` только когда `archived_at <= now`.
         *
         *     Допустимо из любого статуса, кроме `archived`.
         *     Только владелец (`FormPolicy.update`).
         */
        post: operations["archiveForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Достать форму из архива
         * @description Сбрасывает `archived_at` в `NULL`. Статус после этого определяется
         *     сохранённым `published_at`: форма, заархивированная опубликованной,
         *     снова становится `published` и публичной.
         *
         *     Работает и когда архивация только запланирована (`archived_at` в
         *     будущем) — это то же самое действие, отмена факта архивации. Поэтому
         *     правило `canUnarchive` смотрит на саму колонку, а не на статус, и
         *     единственное из четырёх не нуждается в текущем времени.
         *
         *     Тело запроса не требуется. Только владелец (`FormPolicy.update`).
         */
        post: operations["unarchiveForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/{formId}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
            };
            cookie?: never;
        };
        /**
         * Список ответов формы
         * @description Постраничная таблица ответов для автора формы. Сортировка
         *     `created_at DESC`.
         *
         *     Владение проверяет сам `FormResponseScope`: помимо совпадения по
         *     `form_id` он требует, чтобы форма входила в
         *     `SELECT id FROM forms WHERE user_id = ?`. Поэтому чужая форма и
         *     несуществующий `formId` одинаково дают не 404 и не 403, а пустую
         *     страницу с `total: 0` — существование формы не подтверждается.
         */
        get: operations["listFormResponses"];
        put?: never;
        /**
         * Отправить заполненную форму
         * @description Точка входа публичного сценария заполнения. Токен необязателен — форму
         *     проходит аноним.
         *
         *     `FormResponsePolicy.create` проверяет, видна ли ему сама форма
         *     (`FormPolicy.view`): в опубликованную ответ примут у кого угодно, в
         *     черновик — только у автора формы, и для этого он должен предъявить токен.
         *
         *     Несуществующий `formId` неотличим от недоступного: проверка видимости
         *     идёт первой, поэтому анонимный запрос получает 401, а запрос с чужим
         *     токеном — 403.
         *
         *     Валидация двухступенчатая: сначала Zod-схема тела, затем сверка ответов
         *     со схемой формы (`validateFormResponse`) — типы, `required`, границы
         *     длины и чисел, допустимые `choices`, отсутствие неизвестных полей.
         *
         *     Ошибки второй ступени приходят как 400 со списком `{ field, message }`
         *     в поле `details`.
         */
        post: operations["submitFormResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/{formId}/responses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
                /** @description Идентификатор ответа */
                id: components["parameters"]["ResponseId"];
            };
            cookie?: never;
        };
        /**
         * Получить один ответ
         * @description Токен необязателен: пока ответ не отправлен, право на него даёт знание
         *     его `id` — так респондент возвращается к сохранённому черновику, не
         *     заводя аккаунта.
         *
         *     Сначала сверяется принадлежность ответа форме из пути, затем решает
         *     `FormResponsePolicy.view`:
         *
         *     | Состояние ответа | Кто получает доступ |
         *     |---|---|
         *     | Черновик (`submittedAt` = `null`) | любой, кому видна форма (`FormPolicy.view`) |
         *     | Отправленный | только автор формы |
         *
         *     Реальную энтропию даёт только `id` ответа: `formId` секретом не является,
         *     он лежит в ссылке на заполнение.
         */
        get: operations["getFormResponse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить существующий ответ
         * @description Дозаполнение черновика и его отправка: клиент шлёт `submittedAt` тем же
         *     вызовом, которым сохраняет последние ответы. `updatedAt` обновляется
         *     триггером БД.
         *
         *     Правила доступа те же, что у `GET /:id`: черновик правит любой, кому
         *     видна форма, отправленный ответ — только автор формы
         *     (`FormResponsePolicy.update`).
         *
         *     Частичное обновление: переданные поля перезаписывают текущие значения.
         *     Пустое тело отклоняется миддлварой `validate` (400).
         *
         *     `answers` сверяются со схемой формы через `validateFormResponse`; если
         *     поле не передано, проверяются уже сохранённые ответы.
         */
        patch: operations["updateFormResponse"];
        trace?: never;
    };
    "/api/forms/{formId}/ai/generate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Сгенерировать схему формы по текстовому запросу
         * @description Помощник конструктора: по описанию на естественном языке модель
         *     возвращает готовую схему. Текущая схема формы отправляется вместе с
         *     запросом, поэтому эндпоинт годится и для правки существующей формы.
         *
         *     Результат **не сохраняется**: применяет схему клиент отдельным
         *     `PATCH /api/forms/{id}`.
         *
         *     Доступ — только владельцу формы (`FormPolicy.update`). Порядок внутри:
         *     разбор тела → форма и владение → проверка квоты → запрос к модели →
         *     списание квоты. Неудачный запрос к модели квоту не тратит.
         *
         *     Запрос к провайдеру может занять заметное время: при 429 сервис делает
         *     до двух повторов с учётом `Retry-After`, общий таймаут — `AI_TIMEOUT_MS`
         *     (по умолчанию 60 секунд).
         */
        post: operations["generateFormSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/limit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Остаток суточной квоты запросов к ИИ
         * @description Показ счётчика в конструкторе и блокировка кнопки генерации до
         *     наступления `resetAt`. Квота считается по владельцу токена, счётчик
         *     живёт в Redis и обнуляется в полночь.
         */
        get: operations["getAiLimit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms/{formId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Поставить в очередь выгрузку ответов в XLSX
         * @description Асинхронный эндпоинт: возвращает `Job`, а не файл. Полный сценарий:
         *
         *     ```
         *     POST /api/forms/{formId}/export   → 202 { id, status: "pending" }
         *     GET  /api/jobs/{id}               → polling до status === "succeeded"
         *     GET  /api/jobs/{id}/download      → сам .xlsx
         *     ```
         *
         *     Доступ проверяется через `FormPolicy.update` — экспорт разрешён только
         *     владельцу формы, даже если форма опубликована.
         *
         *     Тело запроса не читается: `validate` на роуте не подключён.
         *
         *     Колонки листа: `ID`, `Создан`, `Отправлен`, далее по одной на каждый
         *     элемент схемы (заголовок — `label`).
         *
         *     Ограничения воркера проявляются как `status: "failed"`, а не как
         *     HTTP-ошибка: больше 500 000 строк → `EXPORT_TOO_LARGE`, форма удалена
         *     между постановкой и выполнением → `FORM_NOT_FOUND`.
         */
        post: operations["exportFormResponses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список фоновых задач текущего пользователя
         * @description `JobScope` ограничивает выборку `user_id = <текущий>`. Сортировка
         *     `created_at DESC`.
         *
         *     Создать задачу напрямую нельзя: `POST /api/jobs` не существует, задачи
         *     появляются только через `POST /api/forms/{formId}/export`.
         */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор фоновой задачи */
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /**
         * Состояние одной задачи
         * @description Основной эндпоинт для polling прогресса. Разумный интервал — 1–2 секунды:
         *     воркер пишет прогресс в БД не чаще, чем раз в `syncIntervalMs = 1000`.
         *
         *     Доступ — только владельцу (`JobPolicy.view`).
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор фоновой задачи */
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запросить отмену задачи
         * @description Семантика зависит от текущего статуса:
         *
         *     - `pending` — мгновенно переводится в `cancelled`, проставляется `finishedAt`;
         *     - `running` — проставляется `cancel_requested_at`; воркер увидит флаг при
         *       следующем отчёте о прогрессе и прервётся через `AbortSignal`.
         *       В ответе статус останется `running`;
         *     - терминальный (`succeeded` / `failed` / `cancelled`) — 400.
         *
         *     Тело запроса не требуется.
         */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор фоновой задачи */
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /**
         * Скачать файл-результат задачи
         * @description Вызывать после того, как `GET /api/jobs/{id}` вернул `status: "succeeded"`
         *     и непустой `result.file`.
         *
         *     Ссылку нельзя передать третьему лицу: она требует заголовка
         *     `Authorization`, поэтому прямая вставка в `<a href>` или `window.open`
         *     не сработает — скачивайте через `fetch` + `Blob`.
         *
         *     Имя файла — `export-<YYYY-MM-DD>.xlsx` по дню выполнения задачи.
         *     То же имя лежит в `result.file.name`.
         *
         *     Если поток оборвался **после** отправки заголовков, тело будет обрезанным,
         *     а соединение разорванным — JSON-ответа об ошибке в этом случае не будет.
         */
        get: operations["downloadJobResultFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Ошибка, прошедшая через `errorHandler` — то есть любой наследник
         *     `BaseError`, брошенный контроллером или сервисом.
         */
        DomainError: {
            /** @enum {string} */
            code: "BAD_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "TOO_MANY_REQUESTS" | "SERVICE_UNAVAILABLE" | "INTERNAL_SERVER_ERROR";
            message: string;
            /**
             * @description Присутствует у `BadRequestError` и `TooManyRequestsError`, если был
             *     передан. Для ошибок валидации это `ZodError.issues` (Zod 4) как
             *     есть: `path` — массив сегментов пути до поля, для вложенных схем
             *     глубокий (`["schema", "pages", 0, "elements", 1, "name"]`). Для
             *     ошибок сверки ответа со схемой формы — список `{ field, message }`.
             */
            details?: unknown;
            /** @description Присутствует только при `DEBUG=true` */
            stack?: string[];
        };
        /** @description Ответ `AuthMiddleware` / `OptionalAuthMiddleware` */
        AuthError: {
            /** @enum {string} */
            message: "Missing or invalid authorization header" | "Token not provided" | "Malformed authorization header" | "Invalid, expired or revoked API token";
        };
        /**
         * @example {
         *       "total": 137,
         *       "page": 2,
         *       "limit": 20,
         *       "totalPages": 7
         *     }
         */
        PaginationMeta: {
            /**
             * @description `COUNT(*)` с теми же scope и filter, что и у выборки — согласован
             *     с фильтрами и не «протекает» за границы scope.
             */
            total: number;
            page: number;
            limit: number;
            /** @description `ceil(total / limit)` */
            totalPages: number;
        };
        PaginatedResult: {
            data: unknown[];
            meta: components["schemas"]["PaginationMeta"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description Источник — `userDto.responseSchema` + `userMapper`
         * @example {
         *       "id": "8f14e45f-ceea-467a-9c31-2b1b5f9dfc02",
         *       "email": "user@example.com",
         *       "createdAt": "2026-07-25T10:02:25.000Z"
         *     }
         */
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateApiTokenRequest: {
            name: string;
            /**
             * Format: date-time
             * @description `z.coerce.date().nullable().optional()`. `null` или отсутствие поля —
             *     бессрочный токен.
             */
            expiresAt?: string | null;
        };
        /**
         * @description Источник — `apiTokenDto.responseSchema` + `apiTokenMapper`. Ни `userId`,
         *     ни `type`, ни хранимый хеш наружу не уходят; поля `token` здесь нет вовсе.
         */
        ApiToken: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * Format: date-time
             * @description `null` — токен бессрочен. Токены из `login` живут 24 часа.
             *     Проверяется на каждом запросе в `ApiTokenService.validateToken`.
             */
            expiresAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description Ответ на выпуск токена — `POST /api/auth/login` и `POST /api/tokens`.
         *     Отдельная схема (`issuedApiTokenSchema`) и отдельный маппер
         *     (`toIssuedApiTokenResponse`), потому что это единственный момент, когда
         *     секрет уходит наружу.
         */
        IssuedApiToken: components["schemas"]["ApiToken"] & {
            /**
             * @description **Plaintext-токен**: `randomBytes(32).toString("base64url")`,
             *     43 символа `[A-Za-z0-9_-]`. Показывается ровно один раз —
             *     в БД лежит только `sha256(token)`.
             */
            token: string;
        };
        /**
         * @description Вычисляется на лету в `form.domain.ts`, в БД не хранится:
         *
         *     | Значение | Условие |
         *     |---|---|
         *     | `archived` | `archivedAt !== null && archivedAt <= now` |
         *     | `draft` | `publishedAt === null` |
         *     | `published` | `publishedAt <= now` |
         *     | `scheduled` | `publishedAt > now` |
         *
         *     Переходы: `draft`/`scheduled` → `published` через
         *     `POST /api/forms/{id}/publish`, любой статус → `archived` через
         *     `POST /api/forms/{id}/archive`. Оба обратимы — `unpublish` и
         *     `unarchive` сбрасывают соответствующую колонку в `NULL`.
         * @enum {string}
         */
        FormStatus: "draft" | "scheduled" | "published" | "archived";
        /**
         * @description Рекурсивное условие видимости: либо правило, либо композиция `and`/`or`.
         *     Сервер хранит условия и отдаёт их вместе со схемой; вычисление видимости
         *     выполняется на клиенте.
         */
        Condition: {
            field: string;
            /** @enum {string} */
            operator: "equals" | "notEquals" | "greaterThan" | "greaterThanOrEqual" | "lessThan" | "lessThanOrEqual" | "contains" | "notContains" | "empty" | "notEmpty";
            /** @description Не требуется для `empty` / `notEmpty` */
            value?: string | number | boolean | string[];
        } | {
            and: components["schemas"]["Condition"][];
        } | {
            or: components["schemas"]["Condition"][];
        };
        FormElementBase: {
            /** @description Ключ этого элемента в `FormResponse.answers` */
            name: string;
            label: string;
            /** @default false */
            required: boolean;
            placeholder?: string;
            visibleIf?: components["schemas"]["Condition"];
        };
        ChoiceOption: {
            value: string;
            text: string;
        };
        TextFormElement: components["schemas"]["FormElementBase"] & {
            /** @enum {string} */
            type: "text" | "email" | "textarea";
            validation?: {
                minLength?: number;
                maxLength?: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TextFormElement";
        };
        NumberFormElement: components["schemas"]["FormElementBase"] & {
            /** @constant */
            type: "number";
            validation?: {
                min?: number;
                max?: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NumberFormElement";
        };
        ChoiceFormElement: components["schemas"]["FormElementBase"] & {
            /**
             * @description `dropdown` и `radiogroup` ожидают ответ-строку, `checkbox` —
             *     массив строк.
             * @enum {string}
             */
            type: "dropdown" | "radiogroup" | "checkbox";
            choices: components["schemas"]["ChoiceOption"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ChoiceFormElement";
        };
        /** @description Дискриминированное объединение по `type` */
        FormElement: components["schemas"]["TextFormElement"] | components["schemas"]["NumberFormElement"] | components["schemas"]["ChoiceFormElement"];
        FormPage: {
            name: string;
            title?: string;
            visibleIf?: components["schemas"]["Condition"];
            elements: components["schemas"]["FormElement"][];
        };
        /** @description Хранится в `forms.schema` (JSONB), валидируется `formSchemaObject` */
        FormSchema: {
            pages: components["schemas"]["FormPage"][];
        };
        /** @description Тело `POST /api/forms` (`formDto.createSchema`). */
        FormWriteRequest: {
            /** @description Обрезается по краям (`trim`) */
            title: string;
            schema: components["schemas"]["FormSchema"];
            /**
             * @description Произвольные настройки. Содержимое не валидируется
             * @default {}
             */
            settings: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Тело `PATCH /api/forms/{id}` (`formDto.updateSchema`) — те же поля, что
         *     и при создании, но без умолчания у `settings`: умолчание Zod при
         *     обновлении затирало бы настройки пустым объектом.
         *
         *     `publishedAt` и `archivedAt` через этот роут не пишутся: их нет в схеме,
         *     и Zod отбрасывает их ещё до репозитория.
         */
        FormUpdateRequest: {
            /** @description Обрезается по краям (`trim`) */
            title?: string;
            schema?: components["schemas"]["FormSchema"];
            /** @description Произвольные настройки. Содержимое не валидируется */
            settings?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Тело переходов `publish` и `archive` (`formLifecycleSchema`).
         *     Необязательно целиком: без него переход происходит в момент вызова.
         *
         *     Разбирается не миддлварой `validate`, а самим контроллером
         *     (`resolveTransitionDate`) — `validate` отклоняет пустой объект,
         *     из-за чего вызов без тела получал бы 400.
         */
        FormLifecycleRequest: {
            /**
             * Format: date-time
             * @description Момент перехода, ISO 8601. Дата в будущем даёт отложенный переход:
             *     `scheduled` для публикации, отложенную архивацию для `archive`.
             *     Приводится через `z.coerce.date()`, поэтому строка принимается.
             */
            date?: string;
        };
        /**
         * @description Источник — `formDto.responseSchema` + `formMapper`. Поле `updatedAt`
         *     есть в таблице и в типе `Form`, но в response-схему не входит.
         */
        Form: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            title: string;
            schema: components["schemas"]["FormSchema"];
            settings: {
                [key: string]: unknown;
            };
            status: components["schemas"]["FormStatus"];
            /** @description `status === "published"` */
            isPublic: boolean;
            /**
             * Format: date-time
             * @description Выставляется вызовом `POST /api/forms/{id}/publish`
             */
            publishedAt: string | null;
            /**
             * Format: date-time
             * @description Выставляется вызовом `POST /api/forms/{id}/archive`
             */
            archivedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Значение одного ответа */
        FormResponseAnswer: string | number | boolean | string[];
        /** @description Тело `POST` (`formResponseDto.createSchema`). */
        FormResponseWriteRequest: {
            /** @description Плоский словарь «`name` элемента схемы → ответ» */
            answers: {
                [key: string]: components["schemas"]["FormResponseAnswer"];
            };
            /**
             * @description Произвольные данные клиента, не валидируются
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description `z.coerce.date()` — ISO-строка принимается. `null` или отсутствие
             *     трактуется как черновик ответа; сервер поле не выставляет.
             */
            submittedAt?: string | null;
        };
        /**
         * @description Тело `PATCH` (`formResponseDto.updateSchema`) — те же поля, что и при
         *     создании, но без умолчания у `metadata`: умолчание Zod при обновлении
         *     затирало бы метаданные пустым объектом.
         */
        FormResponseUpdateRequest: {
            /** @description Плоский словарь «`name` элемента схемы → ответ» */
            answers?: {
                [key: string]: components["schemas"]["FormResponseAnswer"];
            };
            /** @description Произвольные данные клиента, не валидируются */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description `z.coerce.date()` — ISO-строка принимается. `null` или отсутствие
             *     трактуется как черновик ответа; сервер поле не выставляет.
             */
            submittedAt?: string | null;
        };
        /**
         * @description Источник — `formResponseDto.responseSchema` + `formResponseMapper`.
         * @example {
         *       "id": "b7a3c2d1-8e4f-4a5b-9c6d-7e8f9a0b1c2d",
         *       "formId": "3c1a7b1e-4f2d-4e8a-9c1b-0a2d3e4f5a6b",
         *       "answers": {
         *         "full_name": "Иван Иванов",
         *         "age": 27,
         *         "topics": [
         *           "backend"
         *         ]
         *       },
         *       "metadata": {},
         *       "submittedAt": "2026-08-16T18:30:00.000Z",
         *       "createdAt": "2026-08-16T18:29:41.000Z",
         *       "updatedAt": "2026-08-16T18:30:00.000Z"
         *     }
         */
        FormResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            formId: string;
            answers: {
                [key: string]: components["schemas"]["FormResponseAnswer"];
            };
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description `null` — черновик ответа. От этого поля зависит доступ: черновик
             *     открыт всем, кому видна форма, отправленный ответ — только автору
             *     формы.
             */
            submittedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Обновляется триггером БД `form_responses_set_updated_at`
             */
            updatedAt: string;
        };
        /**
         * @description Ограничено CHECK-констрейнтом в БД. Терминальные статусы —
         *     `succeeded`, `failed`, `cancelled`: задача в них больше не меняется.
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * @description Файл-результат. Внутренний ключ хранилища (`key`) в ответ не попадает —
         *     Zod-схема его отбрасывает.
         */
        JobResultFile: {
            name: string;
            size: number;
            mimeType: string;
        };
        JobError: {
            /**
             * @description Известные коды: `INVALID_PAYLOAD`, `UNKNOWN_JOB_TYPE`,
             *     `ENQUEUE_FAILED`, `FORM_NOT_FOUND`, `EXPORT_TOO_LARGE`,
             *     `INTERNAL_ERROR`.
             */
            code: string;
            message: string;
            details?: unknown;
        };
        /**
         * @description Источник — `jobDto.responseSchema` + `jobMapper`. Внутренние поля
         *     `payload`, `userId`, `idempotencyKey`, `cancelRequestedAt` и
         *     `result.file.key` в ответ не попадают.
         * @example {
         *       "id": "d4e5f6a7-b8c9-4d0e-9f1a-2b3c4d5e6f70",
         *       "type": "form-responses.export",
         *       "status": "succeeded",
         *       "progress": 100,
         *       "processedCount": 1348,
         *       "totalCount": 1348,
         *       "result": {
         *         "file": {
         *           "name": "export-2026-08-16.xlsx",
         *           "size": 184320,
         *           "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
         *         },
         *         "rowCount": 1348
         *       },
         *       "error": null,
         *       "createdAt": "2026-08-16T18:40:00.000Z",
         *       "startedAt": "2026-08-16T18:40:01.000Z",
         *       "finishedAt": "2026-08-16T18:40:12.000Z"
         *     }
         */
        Job: {
            /** Format: uuid */
            id: string;
            /** @example form-responses.export */
            type: string;
            status: components["schemas"]["JobStatus"];
            /**
             * @description `100` при `succeeded`; `null`, пока `totalCount` неизвестен; иначе
             *     `min(99, floor(processedCount / totalCount * 100))` — намеренно не
             *     даёт 100 % до фактического завершения.
             */
            progress: number | null;
            processedCount: number;
            totalCount: number | null;
            result: {
                file?: components["schemas"]["JobResultFile"];
                /** Format: uuid */
                formId?: string;
                rowCount?: number;
                elementsCount?: number;
            } | null;
            error: components["schemas"]["JobError"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
        };
        AiGenerateRequest: {
            /** @description Описание нужной формы или правки на естественном языке */
            prompt: string;
        };
        AiGenerateResponse: {
            /**
             * @description `ok` — схема получена; `unsupported` — задача вне возможностей
             *     схемы; `ambiguous` — запрос непонятен и нужен уточняющий вопрос.
             * @enum {string}
             */
            status: "ok" | "unsupported" | "ambiguous";
            /** @description Текст для показа пользователю */
            message: string;
            /**
             * @description Готовая схема при `status: "ok"`, иначе `null`. Проходит тот же
             *     `formSchemaObject`, что и `POST /api/forms`, поэтому её можно
             *     отправить в форму как есть.
             */
            schema: components["schemas"]["FormSchema"] | null;
        };
        AiLimit: {
            /** @description Суточный лимит на пользователя (`AI_DAILY_LIMIT_PER_USER`) */
            limit: number;
            used: number;
            /** @description `max(limit - used, 0)` */
            remaining: number;
            /**
             * Format: date-time
             * @description Ближайшая полночь — момент обнуления счётчика
             */
            resetAt: string;
        };
    };
    responses: {
        /** @description Тело запроса не прошло валидацию. Список проблем лежит в `details`. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DomainError"];
            };
        };
        /**
         * @description Query-строка не прошла валидацию по `findSchema`: нечисловые или
         *     выходящие за границы `page` / `limit`, значение вне enum, неразбираемая
         *     дата.
         */
        InvalidQuery: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "Validation failed",
                 *       "details": [
                 *         {
                 *           "code": "too_big",
                 *           "path": [
                 *             "limit"
                 *           ],
                 *           "message": "Too big: expected number to be <=100"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["DomainError"];
            };
        };
        /** @description Формы с таким `id` не существует */
        FormNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Resource not found"
                 *     }
                 */
                "application/json": components["schemas"]["DomainError"];
            };
        };
        /** @description Некорректный запрос (например, пустой path-параметр) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "Route parameter \"id\" is required"
                 *     }
                 */
                "application/json": components["schemas"]["DomainError"];
            };
        };
        /**
         * @description Нет заголовка `Authorization`, токен битый, просроченный или отозванный.
         *     Тело формируется `AuthMiddleware` в обход `errorHandler`, поэтому
         *     содержит только `message`.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthError"] | components["schemas"]["DomainError"];
            };
        };
        /** @description Токен валиден, но ресурс принадлежит другому пользователю */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FORBIDDEN",
                 *       "message": "You do not have permission to access this resource"
                 *     }
                 */
                "application/json": components["schemas"]["DomainError"];
            };
        };
        /** @description Ресурс не найден */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Resource not found"
                 *     }
                 */
                "application/json": components["schemas"]["DomainError"];
            };
        };
        /**
         * @description Превышен лимит частоты запросов. Окно везде — 60 секунд. Общий лимит
         *     `/api`, вход и работа с черновиком ответа считаются по IP, экспорт —
         *     по владельцу токена.
         */
        TooManyRequests: {
            headers: {
                /** @description Состояние лимита (draft-8) */
                RateLimit?: string;
                /** @description Описание политики (draft-8) */
                "RateLimit-Policy"?: string;
                /** @description Секунды до сброса окна */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "TOO_MANY_REQUESTS",
                 *       "message": "Too many requests"
                 *     }
                 */
                "application/json": components["schemas"]["DomainError"];
            };
        };
        /** @description Исчерпан суточный лимит запросов к ИИ */
        AiQuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "TOO_MANY_REQUESTS",
                 *       "message": "Суточный лимит запросов к ИИ исчерпан",
                 *       "details": {
                 *         "limit": 20,
                 *         "resetAt": "2026-08-21T00:00:00.000Z"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["DomainError"];
            };
        };
        /**
         * @description AI-сервис недоступен, ответил ошибкой или вернул неразбираемый JSON.
         *     Подробности уходят в лог, наружу не отдаются.
         */
        AiUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "SERVICE_UNAVAILABLE",
                 *       "message": "AI-сервис временно недоступен"
                 *     }
                 */
                "application/json": components["schemas"]["DomainError"];
            };
        };
    };
    parameters: {
        /** @description Номер страницы, начиная с 1 */
        Page: number;
        /**
         * @description Размер страницы. Значение приводится `z.coerce.number()`; нечисловое,
         *     неположительное или большее `100` даёт 400.
         */
        Limit: number;
        /** @description Идентификатор API-токена */
        TokenId: string;
        /** @description Идентификатор формы */
        FormId: string;
        /** @description Идентификатор родительской формы */
        ParentFormId: string;
        /** @description Идентификатор ответа */
        ResponseId: string;
        /** @description Идентификатор фоновой задачи */
        JobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Процесс жив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "user@example.com",
                 *       "password": "password"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Токен выпущен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "0f0e3a35-9a8a-4d21-9b6a-9f7f1c0b3a10",
                     *       "name": "Session Token (16.08.2026)",
                     *       "expiresAt": "2026-08-17T18:00:00.000Z",
                     *       "createdAt": "2026-08-16T18:00:00.000Z",
                     *       "token": "vJ8kQ2mZ5nR7pT1wY4xA6bC9dE0fG3hJ5kL8mN1oP4q"
                     *     }
                     */
                    "application/json": components["schemas"]["IssuedApiToken"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            /** @description Пользователь не найден или пароль неверен */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "UNAUTHORIZED",
                     *       "message": "Authentication error"
                     *     }
                     */
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль пользователя */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listApiTokens: {
        parameters: {
            query?: {
                /** @description Номер страницы, начиная с 1 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Размер страницы. Значение приводится `z.coerce.number()`; нечисловое,
                 *     неположительное или большее `100` даёт 400.
                 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница токенов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResult"] & {
                        data?: components["schemas"]["ApiToken"][];
                    };
                };
            };
            400: components["responses"]["InvalidQuery"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "CI pipeline"
                 *     }
                 */
                "application/json": components["schemas"]["CreateApiTokenRequest"];
            };
        };
        responses: {
            /** @description Токен создан, plaintext возвращается один раз */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d",
                     *       "name": "CI pipeline",
                     *       "expiresAt": null,
                     *       "createdAt": "2026-08-16T18:05:00.000Z",
                     *       "token": "aB3dE6gH9jK2mN5pQ8sT1vW4xY7zA0cD3fG6hJ9kL2m"
                     *     }
                     */
                    "application/json": components["schemas"]["IssuedApiToken"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор API-токена */
                id: components["parameters"]["TokenId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Токен удалён, тело пустое */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listForms: {
        parameters: {
            query?: {
                /** @description Номер страницы, начиная с 1 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Размер страницы. Значение приводится `z.coerce.number()`; нечисловое,
                 *     неположительное или большее `100` даёт 400.
                 */
                limit?: components["parameters"]["Limit"];
                /**
                 * @description Подстрочный поиск по названию, `ILIKE '%title%'`
                 * @example анкета
                 */
                title?: string;
                /**
                 * @description Статус на момент запроса. Колонки под него в БД нет, поэтому фильтр
                 *     повторяет `resolveFormStatus` выражением `CASE` над `published_at`
                 *     и `archived_at`.
                 */
                status?: components["schemas"]["FormStatus"];
                /** @description `created_at >= createdFrom`, включительно */
                createdFrom?: string;
                /** @description `created_at <= createdTo`, включительно */
                createdTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница форм */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResult"] & {
                        data?: components["schemas"]["Form"][];
                    };
                };
            };
            400: components["responses"]["InvalidQuery"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Анкета участника",
                 *       "schema": {
                 *         "pages": [
                 *           {
                 *             "name": "page_1",
                 *             "title": "О себе",
                 *             "elements": [
                 *               {
                 *                 "name": "full_name",
                 *                 "label": "Как вас зовут?",
                 *                 "type": "text",
                 *                 "required": true,
                 *                 "validation": {
                 *                   "minLength": 2,
                 *                   "maxLength": 100
                 *                 }
                 *               },
                 *               {
                 *                 "name": "age",
                 *                 "label": "Сколько вам лет?",
                 *                 "type": "number",
                 *                 "required": false,
                 *                 "validation": {
                 *                   "min": 14,
                 *                   "max": 120
                 *                 }
                 *               },
                 *               {
                 *                 "name": "topics",
                 *                 "label": "Что вам интересно?",
                 *                 "type": "checkbox",
                 *                 "required": false,
                 *                 "choices": [
                 *                   {
                 *                     "value": "backend",
                 *                     "text": "Backend"
                 *                   },
                 *                   {
                 *                     "value": "frontend",
                 *                     "text": "Frontend"
                 *                   }
                 *                 ]
                 *               }
                 *             ]
                 *           }
                 *         ]
                 *       },
                 *       "settings": {}
                 *     }
                 */
                "application/json": components["schemas"]["FormWriteRequest"];
            };
        };
        responses: {
            /** @description Форма создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Form"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Форма */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Form"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Форма удалена, тело пустое */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Анкета участника (2026)"
                 *     }
                 */
                "application/json": components["schemas"]["FormUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённая форма */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Form"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    publishForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "date": "2026-09-01T09:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["FormLifecycleRequest"];
            };
        };
        responses: {
            /** @description Форма в новом состоянии */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Form"];
                };
            };
            /** @description Недопустимый переход или неразбираемая дата */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "BAD_REQUEST",
                     *       "message": "Опубликовать можно только черновик или запланированную форму"
                     *     }
                     */
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["FormNotFound"];
        };
    };
    unpublishForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Форма в черновиках */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Form"];
                };
            };
            /** @description Снимать нечего */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "BAD_REQUEST",
                     *       "message": "Форма не опубликована и не запланирована"
                     *     }
                     */
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["FormNotFound"];
        };
    };
    archiveForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "date": "2026-12-31T00:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["FormLifecycleRequest"];
            };
        };
        responses: {
            /** @description Форма в новом состоянии */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Form"];
                };
            };
            /** @description Недопустимый переход или неразбираемая дата */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "BAD_REQUEST",
                     *       "message": "Форма уже в архиве"
                     *     }
                     */
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["FormNotFound"];
        };
    };
    unarchiveForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор формы */
                id: components["parameters"]["FormId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Форма вне архива */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Form"];
                };
            };
            /** @description Форма не в архиве */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "BAD_REQUEST",
                     *       "message": "Форма не в архиве"
                     *     }
                     */
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["FormNotFound"];
        };
    };
    listFormResponses: {
        parameters: {
            query?: {
                /** @description Номер страницы, начиная с 1 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Размер страницы. Значение приводится `z.coerce.number()`; нечисловое,
                 *     неположительное или большее `100` даёт 400.
                 */
                limit?: components["parameters"]["Limit"];
                /** @description Дополнительное сужение по форме — сама форма уже задана путём */
                formId?: string;
                /**
                 * @description Поиск по значению конкретного ответа:
                 *     `?answer[full_name]=Иван` → `answers ->> 'full_name' ILIKE '%Иван%'`.
                 *     Ключ обязан подходить под правило имени элемента схемы, значение —
                 *     до 500 символов. Несколько ключей соединяются через `AND`.
                 */
                answer?: {
                    [key: string]: string;
                };
                /**
                 * @description Ответ содержит **все** перечисленные поля
                 *     (`jsonb_exists_all`). Принимает одно имя (`?answered=email`) или
                 *     массив (`?answered[]=email&answered[]=phone`).
                 */
                answered?: string | string[];
                /** @description `true` — только отправленные ответы (`submitted_at IS NOT NULL`) */
                submitted?: boolean;
                /** @description `submitted_at >= submittedFrom`, включительно */
                submittedFrom?: string;
                /** @description `submitted_at <= submittedTo`, включительно */
                submittedTo?: string;
            };
            header?: never;
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница ответов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResult"] & {
                        data?: components["schemas"]["FormResponse"][];
                    };
                };
            };
            400: components["responses"]["InvalidQuery"];
            401: components["responses"]["Unauthorized"];
        };
    };
    submitFormResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "answers": {
                 *         "full_name": "Иван Иванов",
                 *         "age": 27,
                 *         "topics": [
                 *           "backend",
                 *           "frontend"
                 *         ]
                 *       },
                 *       "metadata": {
                 *         "locale": "ru-RU"
                 *       },
                 *       "submittedAt": "2026-08-16T18:30:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["FormResponseWriteRequest"];
            };
        };
        responses: {
            /** @description Ответ сохранён */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getFormResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
                /** @description Идентификатор ответа */
                id: components["parameters"]["ResponseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Ответа нет или он принадлежит другой форме */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "NOT_FOUND",
                     *       "message": "Resource not found"
                     *     }
                     */
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    updateFormResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
                /** @description Идентификатор ответа */
                id: components["parameters"]["ResponseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "answers": {
                 *         "full_name": "Иван Петров",
                 *         "age": 28,
                 *         "topics": [
                 *           "backend"
                 *         ]
                 *       },
                 *       "submittedAt": "2026-08-16T19:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["FormResponseUpdateRequest"];
            };
        };
        responses: {
            /** @description Обновлённый ответ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    generateFormSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "prompt": "Анкета участника конференции: имя, email, выбор трека, согласие на рассылку"
                 *     }
                 */
                "application/json": components["schemas"]["AiGenerateRequest"];
            };
        };
        responses: {
            /** @description Ответ модели */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "message": "Добавил четыре поля — имя, email, выбор трека и согласие.",
                     *       "schema": {
                     *         "pages": [
                     *           {
                     *             "name": "page_1",
                     *             "title": "Участник",
                     *             "elements": [
                     *               {
                     *                 "name": "full_name",
                     *                 "label": "Как вас зовут?",
                     *                 "type": "text",
                     *                 "required": true
                     *               },
                     *               {
                     *                 "name": "email",
                     *                 "label": "Email",
                     *                 "type": "email",
                     *                 "required": true
                     *               }
                     *             ]
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["AiGenerateResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["AiQuotaExceeded"];
            503: components["responses"]["AiUnavailable"];
        };
    };
    getAiLimit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Состояние квоты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "limit": 20,
                     *       "used": 3,
                     *       "remaining": 17,
                     *       "resetAt": "2026-08-21T00:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["AiLimit"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    exportFormResponses: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Произвольная строка. Повторный запрос с тем же ключом вернёт **ту же**
                 *     задачу вместо создания новой. Полный ключ собирается как
                 *     `form-responses.export:<userId>:<Idempotency-Key>` и хранится в
                 *     `jobs.idempotency_key` (UNIQUE). Без заголовка каждый вызов создаёт
                 *     новую задачу.
                 * @example export-2026-08-16-a1
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Идентификатор родительской формы */
                formId: components["parameters"]["ParentFormId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задача принята в очередь */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "d4e5f6a7-b8c9-4d0e-9f1a-2b3c4d5e6f70",
                     *       "type": "form-responses.export",
                     *       "status": "pending",
                     *       "progress": null,
                     *       "processedCount": 0,
                     *       "totalCount": null,
                     *       "result": null,
                     *       "error": null,
                     *       "createdAt": "2026-08-16T18:40:00.000Z",
                     *       "startedAt": null,
                     *       "finishedAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["FormNotFound"];
            429: components["responses"]["TooManyRequests"];
            /** @description Очередь фоновых задач недоступна (Redis) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "SERVICE_UNAVAILABLE",
                     *       "message": "Очередь фоновых задач недоступна, попробуйте позже"
                     *     }
                     */
                    "application/json": components["schemas"]["DomainError"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description Номер страницы, начиная с 1 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Размер страницы. Значение приводится `z.coerce.number()`; нечисловое,
                 *     неположительное или большее `100` даёт 400.
                 */
                limit?: components["parameters"]["Limit"];
                /** @description Точное совпадение статуса */
                status?: components["schemas"]["JobStatus"];
                /**
                 * @description Точное совпадение типа. Единственный зарегистрированный обработчик —
                 *     `form-responses.export`.
                 * @example form-responses.export
                 */
                type?: string;
                /** @description Задачи по конкретной форме, `payload ->> 'formId'` */
                formId?: string;
                /** @description `created_at >= createdFrom`, включительно */
                createdFrom?: string;
                /** @description `created_at <= createdTo`, включительно */
                createdTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница задач */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResult"] & {
                        data?: components["schemas"]["Job"][];
                    };
                };
            };
            400: components["responses"]["InvalidQuery"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор фоновой задачи */
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задача */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "d4e5f6a7-b8c9-4d0e-9f1a-2b3c4d5e6f70",
                     *       "type": "form-responses.export",
                     *       "status": "running",
                     *       "progress": 42,
                     *       "processedCount": 567,
                     *       "totalCount": 1348,
                     *       "result": null,
                     *       "error": null,
                     *       "createdAt": "2026-08-16T18:40:00.000Z",
                     *       "startedAt": "2026-08-16T18:40:01.000Z",
                     *       "finishedAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор фоновой задачи */
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Актуальное состояние задачи после запроса отмены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Задача уже завершена */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "BAD_REQUEST",
                     *       "message": "Задача уже завершена, отменять нечего"
                     *     }
                     */
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadJobResultFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Идентификатор фоновой задачи */
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Бинарный поток XLSX */
            200: {
                headers: {
                    /** @description `attachment; filename="export-<YYYY-MM-DD>.xlsx"` */
                    "Content-Disposition"?: string;
                    /** @description Размер файла в байтах, из `storage.stat()` */
                    "Content-Length"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            /** @description Статус задачи не `succeeded` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "BAD_REQUEST",
                     *       "message": "Результат задачи ещё не готов"
                     *     }
                     */
                    "application/json": components["schemas"]["DomainError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /**
             * @description Задачи нет; у задачи нет файла («У задачи нет файла-результата»);
             *     файл пропал из хранилища («Файл результата отсутствует в хранилище»).
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainError"];
                };
            };
        };
    };
}
